name: shell-lint

on:
  push:
    branches:
      - main
      - '3.**'
  pull_request:
    branches:
      - main
      - '3.**'

jobs:
  shellcheck:
    name: Run Shellcheck on shellscripts
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.4.0

    - uses: ludeeus/action-shellcheck@1.1.0

  shfmt:
    name: Check shellscript formatting
    needs: shellcheck
    env:
      SHFMT_VERSION: 3.0.1
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Install shfmt
      run: |
        sudo wget "https://github.com/mvdan/sh/releases/download/v${SHFMT_VERSION}/shfmt_v${SHFMT_VERSION}_linux_amd64" -O /usr/local/bin/shfmt
        sudo chmod +x /usr/local/bin/shfmt

    - name: Check .sh files
      run: shfmt -d .
